version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: vfx-backend
    ports:
      - "4005:4005"
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    devices:
      - nvidia.com/gpu=all
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - HUGGINGFACE_HUB_TOKEN=${HF_TOKEN}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    command: sh -c "pip install -r requirements.txt && uvicorn app:app --host 0.0.0.0 --port 4005 --reload"

  frontend-dev:
    image: docker.io/library/node:18-alpine
    container_name: vfx-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    depends_on:
      - backend

volumes:
  frontend_node_modules: